apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-example
  labels:
    app: python-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-example
  template:
    metadata:
      labels:
        app: python-example
      annotations:
        instrumentation.opentelemetry.io/inject-python: "instrumentation-testpythonsolution"
    spec:
      containers:
        - name: python-example
          image: pavolloffay/python-helloworld:1
          ports:
            - containerPort: 80