apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: instrumentation-testpythonsolution
spec:
  env:
#    - name: OTEL_EXPORTER_OTLP_TIMEOUT
#      value: "20"
  exporter:
    endpoint: http://otel-collector.ploffay.svc.cluster.local:4317 # <--- USE FQDN TO DEAL WITH HTTP PROXY
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  python:
#    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-python:0.48b0
    image: pavolloffay/python-inst:1
    env:
      # Required if endpoint is set to 4317.
      # Python autoinstrumentation uses http/proto by default
      # so data must be sent to 4318 instead of 4317.
      # - name: OTEL_EXPORTER_OTLP_PROTOCOL
      #   value: grpc
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "http://otel-collector.ploffay.svc.cluster.local:4318"
      - name: OTEL_SERVICE_NAME
        value: testpythonsolution
      # - name: OTEL_LOGS_EXPORTER
      #   value: 'otlp'
#      - name: OTEL_TRACES_EXPORTER
#        value: 'otlp'
#      - name: OTEL_METRICS_EXPORTER
#        value: 'otlp'
#      - name: OTEL_PYTHON_LOG_LEVEL
#        value: DEBUG
#      - name: OTEL_LOG_LEVEL
#        value: DEBUG
